### ISSUE TITLE
:dog does not work

### ISSUE THREAD

**Issue by Dylan56202** [Sceleratis/Adonis#174]
:dog used to turn you into a dog, but it's broken and just removes your clothes

**Comment by joritochip** [comment]
Are you using R6 or R15?

**Comment by Dylan56202** [comment]
I tested it on both R6 and R15 and it's broken for both

**Comment by TheLegendarySpark** [comment]
I've fixed the ``dog`` command. Thanks to Kohl's Admin ``dog`` command, I replicated it to Adonis. Refer to https://github.com/Sceleratis/Adonis/pull/178

**Comment by Dylan56202** [comment]
The command is still broken even after the fix, nothing happens when you use it.
