### ISSUE TITLE
Adonis's library URL is outdated and does not match the one in README markdown

### ISSUE THREAD

**Issue by WaviestBalloon** [Sceleratis/Adonis#840]
The Adonis library URL is outdated, (https://www.roblox.com/library/2373505175/Adonis-Loader-Sceleratis-Davey-Bones)
![image](https://user-images.githubusercontent.com/31796727/176268759-33551643-ccc5-4f48-a7b0-8e0ce2810578.png)

It should be updated to the updated module as listed in the README

**Comment by P3tray** [comment]
@Sceleratis

**Comment by P3tray** [comment]
> 👋 Welcome! It looks like this is your first time creating an issue here. Do expect a maintainer's response in a few days' time regarding your matter.

shut up stinky bot we dont care

**Comment by WaviestBalloon** [comment]
> 👋 Welcome! It looks like this is your first time creating an issue here. Do expect a maintainer's response in a few days' time regarding your matter.

🤮 reis bot

**Comment by P3tray** [comment]
> 👋 Welcome! It looks like this is your first time creating an issue here. Do expect a maintainer's response in a few days' time regarding your matter.

🤮 reis bot

**Comment by Sceleratis** [comment]
fixed

**Comment by WaviestBalloon** [comment]
Issue still not resolved.
![image](https://user-images.githubusercontent.com/31796727/178106972-4c0104b8-d6f7-4b11-ae6c-09211cd461e4.png)
https://www.roblox.com/library/2373505175/Adonis-Loader-Sceleratis-Davey-Bones

**Comment by Expertcoderz** [comment]
> Issue still not resolved.
> ![image](https://user-images.githubusercontent.com/31796727/178106972-4c0104b8-d6f7-4b11-ae6c-09211cd461e4.png)
> https://www.roblox.com/library/2373505175/Adonis-Loader-Sceleratis-Davey-Bones

@Sceleratis Help.

**Comment by Sceleratis** [comment]
Thought I fixed that one sec

**Comment by Expertcoderz** [comment]
@Sceleratis Not fixed; the link in the repo's About section still leads to the old loader by Davey_Bones.

**Comment by Sceleratis** [comment]
> @Sceleratis Not fixed; the link in the repo's About section still leads to the old loader by Davey_Bones.

Ahhhhhhhhhhhhh

**Comment by Sceleratis** [comment]
Actually fixed now (don't even need the library link there since it's all in the readme anyway)
